version: "3.8"

services:
  # usersService DB
  users-db:
    image: postgres
    container_name: users-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # usersService app
  users-service:
    build: ./usersService
    container_name: users-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@users-db:5432/users_db
    depends_on:
      - users-db

  # parkingService DB
  parking-db:
    image: postgres
    container_name: parking-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking_db
    ports:
      - "5433:5432"  # (5432 inside container, 5433 outside on your localhost)
    volumes:
      - parking_pgdata:/var/lib/postgresql/data

  # parkingService app
  parking-service:
    build:
      context: ./parkingService/parking-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: parking-service
    ports:
      - "8080:8080"  # (Quarkus HTTP port, optional)
      - "9000:9000"  # (gRPC port for Quarkus)
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://parking-db:5432/parking_db
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
    depends_on:
      - parking-db

volumes:
  pgdata:
  parking_pgdata: